// Generated by tools/make-goldens.py from ccburn. Do not edit; regenerate.
import g0 from './session-safe'
import g1 from './session-depleted'
import g2 from './session-depleted-small'
import g3 from './session-hot'
import g4 from './session-no-history'
import g5 from './weekly'

export const GOLDENS = [g0, g1, g2, g3, g4, g5]
