"""Render golden chart fixtures with the real ccburn, for the TypeScript port to match.

Run with ccburn's own interpreter, from this repo's root, with ccburn checked
out next to it:

    PYTHONHASHSEED=0 ../ccburn/.venv/Scripts/python tools/make-goldens.py   # Windows
    PYTHONHASHSEED=0 ../ccburn/.venv/bin/python tools/make-goldens.py       # macOS / Linux

Each fixture pins the clock, builds ccburn's own LimitData and snapshots,
renders `BurnupChart._create_chart`, and writes the inputs plus every cell
(glyph and foreground colour) to tests/fixtures/golden/<name>.json. Never edit
those files by hand: change a fixture here and regenerate.
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import ccburn.data.models as models_module
import ccburn.display.chart as chart_module
import ccburn.utils.calculator as calculator_module
from ccburn.data.models import LimitData, LimitType, UsageSnapshot
from ccburn.display.chart import BurnupChart
from ccburn.utils.calculator import calculate_burn_metrics

OUT = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "golden"
ANSI = re.compile(r"\x1b\[([0-9;]*)m")
NAMES: list[str] = []


def fixed_clock(now: datetime) -> type[datetime]:
    class Fixed(datetime):
        @classmethod
        def now(cls, tz=None):  # noqa: D102
            return now if tz is None else now.astimezone(tz)

    return Fixed


def parse(ansi: str) -> list[list[tuple[str, int | None]]]:
    """Split plotext's ANSI output into rows of (glyph, foreground) cells."""
    rows: list[list[tuple[str, int | None]]] = []
    for line in ansi.split("\n"):
        if line == "":
            continue
        cells: list[tuple[str, int | None]] = []
        fg: int | None = None
        pos = 0
        for match in ANSI.finditer(line):
            for ch in line[pos : match.start()]:
                cells.append((ch, fg))
            codes = match.group(1).split(";")
            if codes == ["0"]:
                fg = None
            elif len(codes) >= 5 and codes[0] == "38" and codes[1] == "2":
                r, g, b = (int(c) for c in codes[2:5])
                fg = (r << 16) | (g << 8) | b
            pos = match.end()
        for ch in line[pos:]:
            cells.append((ch, fg))
        rows.append(cells)
    return rows


def ms(dt: datetime) -> int:
    return int(round(dt.timestamp() * 1000))


def render(name: str, kind: str, width: int, height: int, now: datetime, resets_at: datetime,
           current_pct: float, history: list[tuple[datetime, float]]) -> None:
    clock = fixed_clock(now)
    chart_module.datetime = clock
    calculator_module.datetime = clock
    models_module.datetime = clock

    limit_type = LimitType.SESSION if kind == "five_hour" else LimitType.WEEKLY
    limit = LimitData(utilization=current_pct / 100.0, resets_at=resets_at, limit_type=limit_type)

    def snapshot(ts: datetime, pct: float) -> UsageSnapshot:
        data = LimitData(utilization=pct / 100.0, resets_at=resets_at, limit_type=limit_type)
        return UsageSnapshot(
            timestamp=ts,
            session=data if kind == "five_hour" else None,
            weekly=data if kind == "seven_day" else None,
            weekly_sonnet=None,
            weekly_opus=None,
        )

    snapshots = [snapshot(ts, pct) for ts, pct in history]
    metrics = calculate_burn_metrics(limit, snapshots)
    chart = BurnupChart(limit, snapshots, explicit_height=height, burn_metrics=metrics)
    rows = parse(chart._create_chart(width, height))

    offset = now.astimezone().utcoffset()
    golden = {
        "name": name,
        "kind": kind,
        "width": width,
        "height": height,
        "tzOffsetMinutes": int(offset.total_seconds() // 60) if offset else 0,
        "now": ms(now),
        "resetsAt": ms(resets_at),
        "percentUsed": current_pct,
        "history": [{"timestamp": ms(ts), "percentUsed": pct} for ts, pct in history],
        "percentPerHour": metrics.percent_per_hour,
        "glyphs": ["".join(ch for ch, _ in row) for row in rows],
        "colors": [[fg for _, fg in row] for row in rows],
    }
    OUT.mkdir(parents=True, exist_ok=True)
    body = json.dumps(golden, ensure_ascii=False, indent=1)
    module = f"// Generated by tools/make-goldens.py from ccburn. Do not edit; regenerate.\nexport default {body}\n"
    (OUT / f"{name}.ts").write_text(module, encoding="utf-8")
    NAMES.append(name)
    print(f"{name}: {len(rows)} rows x {len(rows[0]) if rows else 0} cols, pph={metrics.percent_per_hour:.3f}")
    print("\n".join(golden["glyphs"]))


def every(start: datetime, end: datetime, step: timedelta) -> list[datetime]:
    out, t = [], start
    while t <= end:
        out.append(t)
        t += step
    return out


def main() -> None:
    utc = timezone.utc
    start = datetime(2026, 9, 15, 14, 0, tzinfo=utc)
    resets = start + timedelta(hours=5)
    now = datetime(2026, 9, 15, 16, 30, tzinfo=utc)
    ten = timedelta(minutes=10)

    # 5-hour window, burning slowly: green projection to the reset.
    slow = [(t, round(8.0 * (t - start).total_seconds() / 3600, 1)) for t in every(start, now, ten)]
    render("session-safe", "five_hour", 80, 20, now, resets, slow[-1][1], slow)

    # 5-hour window, burning fast: orange projection, Depleted line.
    fast = [(t, round(24.0 * (t - start).total_seconds() / 3600, 1)) for t in every(start, now, ten)]
    render("session-depleted", "five_hour", 80, 20, now, resets, fast[-1][1], fast)

    # The same, in a smaller pane.
    render("session-depleted-small", "five_hour", 60, 14, now, resets, fast[-1][1], fast)

    # 5-hour window, very hot: red usage line.
    hot = [(t, min(round(38.0 * (t - start).total_seconds() / 3600, 1), 95.0)) for t in every(start, now, ten)]
    render("session-hot", "five_hour", 90, 22, now, resets, hot[-1][1], hot)

    # 5-hour window with a reading but no history to chart: pace and Now only.
    render("session-no-history", "five_hour", 80, 20, now, resets, 30.0, [])

    # Weekly window, 3.5 days in.
    week_reset = datetime(2026, 9, 19, 0, 0, tzinfo=utc)
    week_start = week_reset - timedelta(hours=168)
    week_now = datetime(2026, 9, 15, 12, 0, tzinfo=utc)
    weekly = [(t, round(0.4 * (t - week_start).total_seconds() / 3600, 1)) for t in every(week_start, week_now, timedelta(hours=2))]
    render("weekly", "seven_day", 100, 24, week_now, week_reset, weekly[-1][1], weekly)

    imports = "".join(f"import g{i} from './{n}'\n" for i, n in enumerate(NAMES))
    index = (
        "// Generated by tools/make-goldens.py from ccburn. Do not edit; regenerate.\n"
        f"{imports}\nexport const GOLDENS = [{', '.join(f'g{i}' for i in range(len(NAMES)))}]\n"
    )
    (OUT / "index.ts").write_text(index, encoding="utf-8")


if __name__ == "__main__":
    sys.exit(main())
